---

##################################################
# JUNOS Ansible Module Generic
#
CONNECTION_PORT: 443

##################################################
# Role Specific Variables
#
DEPLOYMENT_TYPE: "07-space_update_policy"
CONFIG_TYPE: "ems"

