---
################################################################################
# YAML with Tasks - By Automation User // MyUser
################################################################################
#
################################################################################
#  tasks:
##########
#- name: JUNOSSpaceConnectivityTest
#  include_role:
#    name: 00-common
#    tasks_from: galaxy-wait_for_conn_30.yml
- name: JUNOSSpaceAddPMContext
  include_tasks: galaxy_uri_space_add_pm_context.yml
  tags:
    - JUNOSSpaceAddPMContext
  register: addpmcontext
- name: PrintJUNOSSpaceAddPMContext
  debug:
    msg: "{{ addpmcontext }}"