---
  - name: Demonstrating variables in Jinja2 Loops
    hosts: localhost
    connection: local
    vars_files:
      - vars.yml
    gather_facts: no
    tasks:
      - name: Create the Jinja2 based template
        template: src=./loopjson.j2 dest=./outputjson.txt
        register: OUTPUT

      - name: Debug Output
        debug:
          var: OUTPUT

      - name: Show Template Results
        debug:
          msg: "{{ lookup('template', './loopjson.j2') }}"
        register: RESULT

      - name: Debug Result
        debug:
          var: RESULT

      - name: Set Fact J2 Template
        set_fact:
          ADDRESS_MEMBERS: "{{ lookup('template', './loopjson.j2') }}"

      - name: Show Fact ADDRESS_MEMBERS
        debug:
          var: ADDRESS_MEMBERS




