---
LOCATION: "TST6B"
STACK: "EXN"
PROTECTED_NET:
  - name: "PROTECTED_NET_{{ LOCATION }}_{{ STACK }}"
    prefix: "192.168.88.0/24"
    inet: 4
  - name: "PROTECTED_NET_{{ LOCATION }}_{{ STACK }}"
    prefix: "192.168.89.0/24"
    inet: 4
  - name: "PROTECTED_NET_{{ LOCATION }}_{{ STACK }}"
    prefix: "2606:ae00:e200:103::/64"
    inet: 6