---
################################################################################
# YAML with Tasks - By Automation User // MyUser
################################################################################
#
################################################################################
#  tasks:
##########
#- name: JUNOSSpaceConnectivityTest
#  include_role:
#    name: 00-common
#    tasks_from: galaxy-wait_for_conn_30.yml
- name: JUNOSSpaceGetDevices
  include_tasks: galaxy_uri_space_get_devices.yml
  tags:
    - JUNOSSpaceGetDevices
  register: getdevices
- name: PrintGetDevices
  debug:
    msg: "{{ getdevices }}"