---
################################################################################
# Nested YAML with Tasks - By Automation User // MyUser
################################################################################
# JUNOS Space EMS Tasks:
#   - JUNOSSPACEASSIGNPOLICY: Log in to JUNOS Space & Assign Policy to Devices
################################################################################
#  Tasks:
################################################################################

################################################################################
# Check Connectivity
################################################################################
  - name: CheckNetConnectivity
    wait_for:
      host: "{{ SPACE_HOST }}"
      port: "{{ SPACE_API_PORT }}"
      timeout: 30

################################################################################
# Galaxy.URI Juniper JUNOS Space Assign Security Policy to Device
################################################################################
# 01. LOGIN TO JUNOS SPACE
################################################################################
  - name: JUNOSSpace-Login
    uri:
      url: "https://{{ SPACE_HOST }}:{{ SPACE_API_PORT }}/api/space/user-management/login"
      method: POST
      force_basic_auth: yes
      status_code: 200
      follow_redirects: all
      user: "{{ SPACE_API_LOGIN_AUTH_USER }}"
      password: "{{ SPACE_API_LOGIN_AUTH_PASS }}"
      return_content: yes
      validate_certs: no
      headers:
        Accept: application/vnd.net.juniper.space.user-management.user-ref+json;version=1
    register: SPACELOGIN

  - name: Debug-JUNOSSpace-Login-JSON
    debug:
      var: SPACELOGIN.json
#      verbosity: 1

  - name: Debug-JUNOSSpace-Login
    debug:
      msg: "{{ SPACELOGIN }}"

  - name: Copy-Debug-JUNOSSpace-Login
    copy:
      content: "{{ SPACELOGIN }}"
      dest: "{{ DEBUG_DIR }}deb.05_01-junos_space_login_{{ CONFIG_TYPE }}.{{ inventory_hostname }}"

  - name: Output-Debug-JUNOSSpace-Login
    copy:
      content: "{{ SPACELOGIN.set_cookie }}"
      dest: "{{ DEBUG_DIR }}output.05_01-junos_space_login_set_cookie{{ CONFIG_TYPE}}.{{ inventory_hostname }}"

  - name: SetFact-Cookie
    set_fact:
      LOGIN_COOKIE: "{{ SPACELOGIN.set_cookie }}"

################################################################################
# 02. GET DEVICE ID
################################################################################
  - name: JUNOSSpace-GetDevices
    uri:
      url: "https://{{ SPACE_HOST }}:{{ SPACE_API_PORT }}/api/juniper/sd/device-management/devices?filter=(name%20eq%20'{{ inventory_hostname }}')"
      method: GET
      validate_certs: no
      headers:
        Accept: application/vnd.juniper.sd.device-management.devices+json;version=2;q=0.02
        Cookie: "{{ LOGIN_COOKIE }}"
#        Cookie: "{{ SPACELOGIN.set_cookie }}"
    register: SpaceGetDevices

  - name: Debug-JUNOSSpace-GetDevices-JSON
    debug:
      var: SpaceGetDevices.json
#      verbosity: 1

  - name: Debug-JUNOSSpace-GetDevices
    debug:
      msg: "{{ SpaceGetDevices }}"

  - name: Copy-Debug-JUNOSSpace-GetDevices
    copy:
      content: "{{ SpaceGetDevices }}"
      dest: "{{ DEBUG_DIR }}deb.05_02-junos_space_get_devices_{{ CONFIG_TYPE }}.{{ inventory_hostname }}"

  - name: Set-SD-DeviceID
    set_fact:
      CONTEXT_DEVICE_ID: "{{ SpaceGetDevices.json.devices.device[0].id }}"

  - name: Debug-Set-SD-DeviceID
    debug:
      msg: "{{ CONTEXT_DEVICE_ID }}"

  - name: Output-Debug-Set-SD-DeviceID
    copy:
      content: "{{ CONTEXT_DEVICE_ID }}"
      dest: "{{ OUTPUT_DIR }}output.05_02-junos_space_get_devices_{{ CONFIG_TYPE}}.{{ inventory_hostname }}"

################################################################################
# 03. GET POLICY ID
################################################################################

  - name: JUNOSSpace-GetPolicy
    uri:
      url: "https://{{ SPACE_HOST }}:{{ SPACE_API_PORT }}/api/juniper/sd/policy-management/firewall/policies?filter=(name%20eq%20'{{ SPACE_API_POLICY_NAME }}')"
      method: GET
      status_code: 200
      follow_redirects: all
      return_content: yes
      body_format: json
      validate_certs: no
      headers:
        Accept: application/vnd.juniper.sd.policy-management.firewall.policies+json;version=2;q=0.02
        Cookie: "{{ LOGIN_COOKIE }}"
#        Cookie: "{{ SPACELOGIN.set_cookie }}"
    register: SpaceGetPolicyID

  - name: Debug-JUNOSSpace-GetPolicy-MSG
    debug:
      msg: "{{ SpaceGetPolicyID }}"

  - name: Debug-JUNOSSpace-GetPolicy-VAR
    debug:
      var: SpaceGetPolicyID
#      verbosity: 1

  - name: Copy-Debug-JUNOSSpace-GetPolicy
    copy:
      content: "{{ SpaceGetPolicyID }}"
      dest: "{{ DEBUG_DIR }}deb.05_03-junos_space_get_policy_{{ CONFIG_TYPE }}.{{ inventory_hostname }}"

  - name: Set-SD-PolicyID
    set_fact:
      CONTEXT_POLICY_ID: "{{ SpaceGetPolicyID.json.policies.policy[0].id }}"

  - name: Debug-Set-SD-PolicyID
    debug:
      msg: "{{ CONTEXT_POLICY_ID }}"

  - name: Output-Debug-Set-SD-PolicyID
    copy:
      content: "{{ CONTEXT_POLICY_ID }}"
      dest: "{{ OUTPUT_DIR }}output.05_03-junos_space_get_policy_id_{{ CONFIG_TYPE}}.{{ inventory_hostname }}"

################################################################################
# 04. ASSIGN POLICY TO DEVICE
################################################################################

  - name: JUNOSSpace-AssignPolicy
    uri:
      url: "https://{{ SPACE_HOST }}:{{ SPACE_API_PORT }}/api/juniper/sd/policy-management/firewall/policies/{{ CONTEXT_POLICY_ID }}/assign-devices"
      method: POST
      status_code: 200, 204
      follow_redirects: all
      return_content: yes
      validate_certs: no
      headers:
        content-type: application/vnd.juniper.sd.policy-management.assign-devices+json;version=2;charset=UTF-8
        Cookie: "{{ LOGIN_COOKIE }}"
#        Cookie: "{{ SPACELOGIN.set_cookie }}"
      body_format: json
      body: >
        {
          "assign-devices" : {
            "add-list" : {
              "device" : [ {
                "id" : "{{ CONTEXT_DEVICE_ID }}",
                "name" : "{{ inventory_hostname }}"
              } ]
            }
          }
        }
    register: SpaceAssignPolicy

#  - name: Debug-JUNOSSpace-AssignPolicy-MSG
#    debug:
#      msg: "{{ SpaceAssignPolicy }}"

  - name: Debug-JUNOSSpace-AssignPolicy-VAR
    debug:
      var: SpaceAssignPolicy
#      verbosity: 1

  - name: Copy-Debug-JUNOSSpace-AssignPolicy
    copy:
      content: "{{ SpaceAssignPolicy }}"
      dest: "{{ DEBUG_DIR }}deb.05_04-junos_space_assign_policy_{{ CONFIG_TYPE }}.{{ inventory_hostname }}"

################################################################################
# 05. LOGOUT
################################################################################
#
  - name: JUNOS_SPACE//LOGOUT
    block:
    - name: JUNOSSpace-Logout
      uri:
        url: "https://{{ SPACE_HOST }}:{{ SPACE_API_PORT }}/api/space/user-management/logout"
        method: POST
        status_code: 200
        validate_certs: no
        headers:
          Cookie: "{{ LOGIN_COOKIE }}"
      register: OUTPUTLOGOUT
    - name: DEBUGLOGOUT
      debug:
        var: OUTPUTLOGOUT
#    when:
    ignore_errors: yes