---
- name: TEST
  connection: local
#  gather_facts: true
  gather_facts: false
  hosts: all
  serial: 0
  vars:
    LOCATION: "TST6B"
    STACK: "EXN"
    PNET:
      - name: "PROTECTED_NET_{{ LOCATION }}_{{ STACK }}"
        prefix: "192.168.88.0/24"
        inet: 4
      - name: "PROTECTED_NET_{{ LOCATION }}_{{ STACK }}"
        prefix: "192.168.89.0/24"
        inet: 4
      - name: "PROTECTED_NET_{{ LOCATION }}_{{ STACK }}"
        prefix: "2606:ae00:e200:103::/64"
        inet: 6

  tasks:
################################################################################
    - name: SETFACTPNET
      set_fact:
        PROTECTED_NET: "{{ PNET }}"
      register: OUTPUTSETFACTPNET
    - name: DEBUGOUTPUTSETFACTPNET
      debug:
        var: OUTPUTSETFACTPNET
    - name: DEBUGPROTECTED_NET
      debug:
        var: PROTECTED_NET
    - name: DEBUGPNET
      debug:
        var: PNET

################################################################################
    - name: J2TEMPLATEJSON
      template: src=1.j2 dest=1.log
      register: OUTPUTJ2TEMPLATEJSON

    - name: PRINTJ2TEMPLATEJSON
      debug:
        var: OUTPUTJ2TEMPLATEJSON

    - name: SETFACTJ2TEMPLATEJSON
      set_fact:
        ADDRESS_JSON: "{{ lookup('template', '1.j2') }}"

    - name: PRINTSETFACTJ2TEMPLATEJSON
      debug:
        var: ADDRESS_JSON











